To Do list: add & remove
MohammadYaser/To-do-List pull request #3
Opened 2023-08-17 17:17 UTC by MohammadYaser

- Remove all hardcoded items from the tasks array.
- Create a new JavaScript file for the new functionality.
- Implement a function for adding a new task (add a new element to the array).
- Implement a function for deleting a task (remove an element from the array).
- Implement a function for editing task descriptions.
- By default new tasks should have the property completed set to false and the property index set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal to 5).
- Deleting a task should update all remaining items' indexes, so they represent the current list order and are unique(i.e. if you're deleting the first task index 1 from the list, the index of the next task(2) should set to 1)..
- All changes to the To Do List should be saved in local storage.

2023-08-17 18:04 UTC, Efiamotu-1 requested changes
Hi @MohammadYaser , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 18:04 UTC, Efiamotu-1 commented on src/assets/trash.png
[OPTIONAL]
- [ ] In your readme file, the live demo section can be removed since there is no link to the live demo of your application. or you could also provide the appropriate working link to your live demo 👍

2023-08-17 18:04 UTC, Efiamotu-1 commented on src/crud.js
> +};
- [ ] When the delete button is clicked and the todo is deleted the screen is not updated to reflect the deleted todo. The deleted todo is only removed from the local storage but not the screen. I kindly suggest you fix this bug as it is not supposed to function this way. At every click of the delete button the todo should be removed from the screen and the local storage updated as well

2023-08-17 18:04 UTC, Efiamotu-1 commented on src/crud.js
> +  };
- [ ] By default your index should start at `1` not `0` which is what you currently have in your project. I kindly suggest you add `1` to the index whenever a new task is added this way your index starts at `1`. 👍

2023-08-17 18:04 UTC, Efiamotu-1 commented on src/crud.js
- [ ] One of your project requirement is to add the functionality of editing tasks. However this has not been implemented in your project. I kindy suggest you add this functionality to your project 👍 ✨

2023-08-17 18:07 UTC, Efiamotu-1 commented on src/crud.js
> +  };
- [ ] Your project currently doesn't have the functionality for editing a task please kindly implement this as It is a [project requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m3_add_remove.md#:~:text=Implement%20a%20function%20for%20editing%20task%20descriptions) 
![ed](https://github.com/MohammadYaser/To-do-List/assets/89055502/669b1b5c-d1a8-4439-8269-30979ff01d5a)

2023-08-17 18:27 UTC, christianbiring1 requested changes
Hi @MohammadYaser , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 

## Highlights
- [ ] Great work on implementing the different functions as required in the project requirements :+1: 
- [ ] Well documented work :+1: :100: 
- [ ] Good work on setting up the project with Webpack :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] Kindly I would suggest you use the default command `start` to run the application instead of `dev` as you just did.
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-17 18:27 UTC, christianbiring1 commented on src/crud.js
> +};
- [ ] As you may notice, when deleting a task, there is this weird behavior in your implementation which is that a task is not been deleted, but when we try to add, that it the time a task is being deleted, Kindly make sure you fix that.

2023-08-19 07:16 UTC, KanzaTahreem approved these changes
# Approved 🙌

Hi @MohammadYaser 

Good job implementing the suggested changes 💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media.tenor.com/xDHCe07zrocAAAAC/congrats-minions.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Styling is looking great
-  ✅ `delete` function is working
-  ✅ Linters are working properly

## Optional suggestions ❕
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-19 07:42 UTC, merged